name: Build .exe with PyInstaller

on:
  push:
    branches:
      - main  # 根据实际需要修改为您使用的分支
  pull_request:
    branches:
      - main  # 根据实际需要修改为您使用的分支

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境来编译 .exe 文件

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files to debug
        run: dir  # 列出当前文件夹内容，以帮助调试

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 选择合适的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install playwright
          python -m playwright install

      - name: Build executable
        run: |
          pyinstaller --onefile fetch_titles.py  # 如果在子目录中，修改路径

      - name: Upload .exe file
        uses: actions/upload-artifact@v3
        with:
          name: fetch_titles-exe
          path: dist/fetch_titles.exe  # 这是生成的 .exe 文件路径

查看全部
